name: Deploy via Self-hosted Runner

on:
  push:
    branches:
      - main

jobs:
  basion-buld-deploy:
    runs-on: [self-hosted]
    
    steps:
    - name: ssh to the basion
      run: |
        ssh azureuser@20.63.24.50 'ssh azureuser@10.0.0.4 "ls"'
    # - name: ssh to the basion
    #   run: |
    #     ssh azureuser@10.0.0.4
    #     ls
  
    - name: Checkout code
      uses: actions/checkout@v3

    - name: check code
      run : |
       pwd
  
    # - name: Tar the source code
    #   run: |
    #     tar -czf git_app_1.tar.gz .
        
    # - name: Backup the sorce code file from the vm
    #   run: |
        
    #     echo "backup the soruce code in vm..."
        # ssh azureuser@20.63.24.50 'ssh azureuser@10.0.0.4 "mv -r ./git_app_1 ./backup/lastBackup/"'
    #     echo "remove the real code from the vm..."
    #     scp -r ./git_app_1.tar.gz "ssh azureuser@20.63.24.50 'ssh azureuser@10.0.0.4 "/home/azureuser/backup/newChanges"'"
        
    
   

        
    #     echo "ssh to basion server..."
    #     ssh azuresuer@20.63.24.50
    #     ssh azureuser@10.0.0.4
        
    #     echo " Copy dist to Bastion server..."
    #     scp -r ./dist azureuser@20.63.24.50:/home/azureuser/
    #     echo " Remove old dist from Private VM..."
    #     ssh azureuser@20.63.24.50 'ssh azureuser@10.0.0.4 "rm -rf /home/azureuser/git_app_1/dist"'
    #     echo "Copy new dist from Bastion to Private VM..."
    #     ssh azureuser@20.63.24.50 'scp -r /home/azureuser/dist azureuser@10.0.0.4:/home/azureuser/git_app_1/'
    #     echo "Remove dist from Bastion server..."
    #     ssh azureuser@20.63.24.50 'rm -rf /home/azureuser/dist'
  

    # - name: Restart Nginx on Private VM
    #   run: |
    #     echo "Restarting Nginx on Private VM....."
    #     ssh azureuser@20.63.24.50 'ssh azureuser@10.0.0.4 "sudo systemctl restart nginx"'
