name: MERN App CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create zip of new code
      run: |
        zip -r new_code.zip . -x "*.git*" "node_modules/*"
        
    - name: Start SSH agent and add key
      run: |
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa
        

    - name: Delete the old code from the vm
      run: |
        ssh azureuser@20.63.24.50 'ssh azureuser@10.0.0.4 "rm -r /home/azureuser/backup/newChanges/*"'
        
    - name: Send new zip to VM (via bastion)
      run: |
        sshpass -p "${{ secrets.VM_PASSWORD }}" rsync -avz -e "ssh -A -J azureuser@20.63.24.50 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
        new_code.zip \
        azureuser@10.0.0.4:~/backup/newChanges/

    - name: ssh to vm and run backup + deploy script
      run: |
       ssh azureuser@20.63.24.50 << 'EOF1'
        ssh azureuser@10.0.0.4 << 'EOF2'
          set -e
          echo "Zipping current git_app_1 to lastBackup..."
          cd ~
          DATE=$(date +%Y-%m-%d)
          zip -r backup/lastBackup/old_code_$DATE.zip git_app_1

          echo "Removing current git_app_1 folder..."
          rm -rf git_app_1

          echo "Extracting new code..."
          unzip backup/newChanges/new_code.zip -d git_app_1

          echo "Installing and building..."
          cd git_app_1
          npm install
          npm run build
          sudo systemctl restart nginx
       EOF2
       EOF1

      
